### PR TITLE
Adding package control metadata.

### LINKED ISSUE #5: Allow installation via Package Control

### PR DESCRIPTION
**Pull request by brodkin**
Fixes #5.

This is really just a starter file, preconfigured for the plugin.  Ideally releases will be tagged and @bradfeehan will update the version and download URL to match the tag.  The file supplied, however, will work.

If this gets merged I will fork the package control repo and add SublimePHPCoverage to it.

### CODE REVIEW

**Comment by bradfeehan** [comment]
:+1:

**Comment by bradfeehan** [comment]
I'll tag an initial release now, but I'm gonna go with v0.1.0 for the first release.

**Comment by bradfeehan** [comment]
I've [tagged](https://github.com/bradfeehan/SublimePHPCoverage/tree/0.1.0) the release, and submitted a [pull request](https://github.com/wbond/package_control_channel/pull/1227) to the Package Control repo.

**Comment by brodkin** [comment]
I think this will be an awesome contribution to the ST community!

**Comment by bradfeehan** [comment]
Absolutely, this is just the kick I needed to actually get some momentum! :smile:

**Comment by bradfeehan** [comment]
The pull request has been merged, it should be in Package Control now (I assume)

**Pull request merged**
